#server:
#  port: 4020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_display?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: dbuser
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    url: jdbc:mysql://localhost:3306/data_display?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    change-log: classpath:config/data_display/master.xml
    enabled: true
    drop-first: false
